name: Pierwsze workflow
on: [push]
jobs:
  sprawdzenie_wersji:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python3 --version
      - name: Check out repository code
        uses: actions/checkout@v3
  test_pylintem:
    runs-on: ubuntu-latest
    steps:
      - name: Pylint action
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt install pylint 
      - run: pylint app.py
      
  obrazdoker:
    runs-on: ubuntu-latest 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build --tag test-flask-app .
            
