name: Pierwsze workflow
on: [push]
jobs:
  sprawdzenie wersji:
    runs-on: ubuntu-latest
    steps:
      -name: Check out repository code
       uses: actions/checkout@v3
      -run: docker --version
      -run: python3 --version
  test pylintem:
    runs-on: ubunt-latest
    steps:
      -name: Check out repository code
       uses: actions/checkout@v3
      -pylint app.py
            
