name: Pierwsze workflow
on: push
jobs:
    sprawdzenie wersji:
		runs-on: ubuntu-latest
		steps:
			-docker --version
			-python3 --version
    test pylintem:
        runs-on: ubunt-latest
        steps:
            -pylint app.py
            
