name: Pierwsze workflow
on: [push]
jobs:
  sprawdzenie_wersji:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python3 --version
      - name: Check out repository code
        uses: actions/checkout@v3
  test_pylintem:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pylint app.py
  obrazdoker:
    runs-on: ubuntu-latest 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build --tag test-flask-app .
            
